# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images/tips/'),
            preserve_default=False,
        ),
    ]
