# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='text',
            field=models.TextField(),
        ),
    ]
