# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160606_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='resume_user',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='user',
            new_name='skill_user',
        ),
    ]
