# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160606_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.AddField(
            model_name='skill',
            name='post',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
