# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160611_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='institution',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='profession',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
