# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160612_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 6, 16, 17, 17, 35, 824389, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
