# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_company_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(),
        ),
    ]
